spring:
  application:
    name: backend

  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        highlight_sql: false
        jdbc:
          time_zone: Asia/Seoul
    #open-in-view: false # OSIV 비활성화

jwt:
  secret: gollagolla-secret-key-must-be-at-least-32-characters-long
  access-token-expiry-ms: 3600000      # 1시간
  refresh-token-expiry-ms: 604800000   # 7일

app:
  share-base-url: https://gollagolla.app/s/
